spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base-db?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  cors:
    allowed-origins: "http://localhost:3000,http://your-production-url.com"
  file:
    images:
      location: public/images/
